# Generated by Django 3.2.18 on 2023-07-31 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Registry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registry_name', models.CharField(help_text="Name of the registry, e.g., 'registryname'.", max_length=255)),
                ('version', models.CharField(help_text="Version number of the registry, e.g., '111'.", max_length=50)),
                ('class_name', models.CharField(help_text="Name of the class, e.g., 'InsureeRegistry'.", max_length=255)),
                ('model', models.CharField(help_text="Model from candidate application that will be used to store data. Example: 'Insuree'", max_length=50)),
                ('fields_mapping', models.JSONField(help_text="Field mapping as a JSON object. Example: {'ID': 'id', 'FirstName': 'otherNames', 'LastName': 'lastName', 'uuid': 'uuid'}.")),
                ('special_fields', models.JSONField(help_text="Special fields that are not covered in a candidate application as a JSON list. Example: ['BirthCertificateID', 'PersonalData'].")),
                ('default_values', models.JSONField(help_text='Default values as a JSON object. Example: {\'family_id\': \'familyId: 1\', \'gender_id\': \'genderId: "U"\', \'dob\': \'1920-04-02\', \'head\': \'head: false\', \'card_issued\': \'cardIssued: false\'}.')),
                ('mutations', models.JSONField(help_text="Mutations as a JSON object. Example: {'create': 'createInsuree', 'delete': 'deleteInsurees', 'update': 'updateInsuree'}.")),
                ('queries', models.JSONField(help_text="Queries as a JSON object. Example: {'get': 'GetInsurees'}.")),
            ],
        ),
    ]
