# Generated by Django 3.2.20 on 2023-08-12 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('govstack_api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='registry',
            name='id_field',
            field=models.CharField(default='undefined', help_text='Model field which contains primary key used by registry for entry recognition. I.e. `chf_id` for Insuree.', max_length=255),
            preserve_default=False,
        ),
    ]
