# Generated by Django 3.2.20 on 2023-08-12 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('govstack_api', '0002_registry_id_field'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registry',
            name='id_field',
            field=models.CharField(help_text='Model field which contains primary key used by registry for entry recognition in GQL notation. I.e. `chfId` for Insuree.', max_length=255),
        ),
    ]
